apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ledger-service.fullname" . }}-config
  labels:
    {{- include "ledger-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
