{{- if .Values.secrets.dbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger-service.fullname" . }}-secret
  labels:
    {{- include "ledger-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
{{- end }}